### ISSUE TITLE
does this happen to use Nulldi's fastplace dll?

### ISSUE THREAD

**Issue by crakced** [Youded-byte/FastPlace-Agent#1]
just a little question

**Comment by Youded-byte** [comment]
No, they work very differently and aren't related to each other. I had made fastplace about a month ago, but decided to release fastplace publicly as a reaction to the DMCA takedown against lunar client qt and some agents. The takedown request is filled with lies and Moonsworth has no right to take down mods that work on both vanilla minecraft, forge and lunar client, just because they feel special. See https://github.com/github/dmca/blob/master/2022/02/2022-02-25-lunar-client.md.

**Comment by crakced** [comment]
Ill read up, thank you for the information!
